name: Trigger CircleCI Vulnerability Scan Pipeline on Release

on:
  release:
    types:
      - published

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CircleCI Pipeline
        run: |
          curl --request POST \                                                 
            --url https://circleci.com/api/v2/project/gh/snyk/code-local-engine/pipeline \
            --header "Circle-Token: ${{ secrets.CIRCLECI_API_KEY }}" \
            --header "content-type: application/json" \
            --data '{"branch":"main","parameters":{"isRC": false, "is-scheduled-scan": true}}'
        env:
          CIRCLECI_API_KEY: ${{ secrets.CIRCLECI_API_KEY }}
